esphome:
  name: esp-temp-primary

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  # use_address: esphome-web-6bd955.local
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP Temp Primary"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80



sensor:
  - platform: dht
    pin: D0
    temperature:
      id: temp_sensor
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 30s


# binary_sensor:
#   - platform: template
#     name: "Heater On"
#     id: heater_on



# climate:
#   - platform: thermostat
#     name: "Thermostat Climate Controller"
#     sensor: temp_sensor
#     min_heating_off_time: 30s
#     min_heating_run_time: 30s
#     min_idle_time: 30s
#     visual:
#       temperature_step: 1
#     heat_action:
#       - binary_sensor.template.publish:
#           id: heater_on
#           state: ON
#     idle_action:
#       - binary_sensor.template.publish:
#           id: heater_on
#           state: OFF
#     default_preset: Home
#     preset:
#       - name: Home
#         default_target_temperature_low: 70 °F
