esphome:
  name: esp-basement-thermostat

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  # use_address: esp-temp.local
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP Basement Temp and Humidity"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80



sensor:
  - platform: dht
    pin: D0
    temperature:
      id: temp_sensor
      name: "Temperature"
    humidity:
      id: humidity_sensor
      name: "Humidity"
    update_interval: 30s


binary_sensor:
  - platform: template
    name: "Heater Call"
    id: heater_call



climate:
  - platform: thermostat
    name: "Temp"
    sensor: temp_sensor
    min_heating_off_time: 30s
    min_heating_run_time: 30s
    min_idle_time: 30s
    heat_deadband: 0.14
    heat_overrun: 0.14
    visual:
      min_temperature: 55째F
      max_temperature: 85째F
      temperature_step: 1째F
    heat_action:
      - binary_sensor.template.publish:
          id: heater_call
          state: ON
    idle_action:
      - binary_sensor.template.publish:
          id: heater_call
          state: OFF
    # default_preset: Home
    # preset:
    #   - name: Home
    #     default_target_temperature_low: 70 째F


