esphome:
  name: esp-griddle

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # use_address: esphome-web-e3b9d3.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp-griddle"
    password: !secret wifi_password

captive_portal:


web_server:
  port: 80



sensor:
  - platform: ntc
    sensor: resistance_sensor
    name: NTC Temperature
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100kOhm
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 6.76kOhm
    name: Resistance Sensor
    reference_voltage: 3.3
  - platform: adc
    id: source_sensor
    pin: A0
    update_interval: 1s
    filters:
      - multiply: 3.1


