esphome:
  name: esp-temp

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  # use_address: esphome-web-6bd955.local
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP Temp and Humidity"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80

# switch:
#   - platform: gpio
#     name: "Living Room Dehumidifier"
#     pin: 2


sensor:
  - platform: dht
    pin: D0
    temperature:
      id: temp_sensor
      name: "T"
    humidity:
      name: "H"
    update_interval: 30s


binary_sensor:
  - platform: template
    name: "H"
    id: heater_on


# switch:
#   - platform: template
#     id: heater_switch
#     name: "Heater On"
#     optimistic: true


climate:
  - platform: thermostat
    name: "Temp"
    sensor: temp_sensor
    min_heating_off_time: 30s
    min_heating_run_time: 30s
    min_idle_time: 30s
    heat_deadband: 0.14
    heat_overrun: 0.14
    visual:
      min_temperature: 16.5
      max_temperature: 24
      temperature_step: 0.5
    heat_action:
      # - switch.turn_on: heater_switch
      - binary_sensor.template.publish:
          id: heater_on
          state: ON
    idle_action:
      # - switch.turn_off: heater_switch
      - binary_sensor.template.publish:
          id: heater_on
          state: OFF
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 70 °F
