esphome:
  name: "esp-air-quality"
  friendly_name: esp-air-quality
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0


# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  # use_address: esp-temp.local
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP Filament Dryer"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80


# Example configuration entry
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003
    update_interval: 120000ms
    pm_1_0:
      name: "pm_1_0"
    pm_2_5:
      name: "pm_2_5"
    pm_10_0:
      name: "pm_10_0"
    pm_0_3um:
      name: "pm_0_3um"
    pm_0_5um:
      name: "pm_0_5um"
    pm_1_0um:
      name: "pm_1_0um"
    pm_2_5um:
      name: "pm_2_5um"
    pm_5_0um:
      name: "pm_5_0um"
    pm_10_0um:
      name: "pm_10_0um"