substitutions:
  name: esp32-bluetooth-proxy-fd11b0
  friendly_name: Bluetooth Proxy 001
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  password: ""


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
